*** conf location
sudo nano /etc/nginx/sites-available/neulibrary.conf

server {
    listen 80;
    server_name 192.168.103.53;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 192.168.103.53;

    client_max_body_size 4G;

    ssl_certificate /etc/ssl/neulibraryssl/cert.pem;
    ssl_certificate_key /etc/ssl/neulibraryssl/key.pem;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/ubuntu/neulibrary/static_files/;
    }

    location /media/ {
        alias /home/ubuntu/neulibrary/media_files/;
    }

    location / {
        include proxy_params;
        # Use the port or socket Daphne is listening on
        proxy_pass http://127.0.0.1:8000;
        
        # Essential for WebSockets (Django Channels)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_redirect off;
        #proxy_set_header Host $host;
        #proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }
}



***
sudo ln -s /etc/nginx/sites-available/neulibrary.conf /etc/nginx/sites-enabled
